// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WalkApp.Data;

#nullable disable

namespace WalkApp.Migrations
{
    [DbContext(typeof(TRWalksDbContext))]
    [Migration("20260221191942_Seeding data for diff and regions")]
    partial class Seedingdatafordiffandregions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WalkApp.Models.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54945523-37de-46c2-94b7-6a016bc7a6b5"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("e0c4b1de-1c76-4885-9397-33d5711f8dd8"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("da73f78b-eea2-434d-a0db-b38543e7c371"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("WalkApp.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1c4b1de-1c76-4885-9397-33d5711f8dd8"),
                            Code = "IC_ANADOLU",
                            Name = "Ic Anadolu"
                        },
                        new
                        {
                            Id = new Guid("a0c4b1de-1c76-4885-9397-33d5711f8dd8"),
                            Code = "KARADENIZ",
                            Name = "Karadeniz"
                        },
                        new
                        {
                            Id = new Guid("b0c4b1de-1c76-4885-9397-33d5711f8dd8"),
                            Code = "AKDENIZ",
                            Name = "Akdeniz"
                        },
                        new
                        {
                            Id = new Guid("c0c4b1de-1c76-4885-9397-33d5711f8dd8"),
                            Code = "MARMARA",
                            Name = "Marmara"
                        },
                        new
                        {
                            Id = new Guid("e0c4b1de-1c76-4885-9397-33d5711f8dd8"),
                            Code = "EGE",
                            Name = "Ege"
                        },
                        new
                        {
                            Id = new Guid("f0c4b1de-1c76-4885-9397-33d5711f8dd8"),
                            Code = "DOGU_ANADOLU",
                            Name = "Dogu Anadolu"
                        });
                });

            modelBuilder.Entity("WalkApp.Models.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("walks");
                });

            modelBuilder.Entity("WalkApp.Models.Walk", b =>
                {
                    b.HasOne("WalkApp.Models.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WalkApp.Models.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
